version: '3.9'

services:
  mysql:
    container_name: "healthMysql"
    image: mysql:5.7
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: 12345
       MYSQL_USER: health
       MYSQL_PASSWORD: solghwiuey
       MYSQL_DATABASE: health
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3333:3306
    expose:
      - 3333
    tty: true
volumes:
  db_data: { }