version: '3.1'

services:
  mysql:
    container_name: "healthMysql"
    image: mysql:5.6
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: 12345
       MYSQL_USER: health
       MYSQL_PASSWORD: solghwiuey
       MYSQL_DATABASE: health
    ports:
      - 3333:3306
    expose:
      - 3333
    tty: true